# Use root/example as user/password credentials
version: '3.1'

services:

services:

  db01:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      TZ: 'Asia/Tokyo'
    volumes:
     - "~/doctest01/db01/db-data:/var/lib/mysql"
    container_name: "db01"

  adminer01:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    container_name: "adminer01"

  web01:
    build: ./web01/build
    restart: always
    ports:
      - 80:80
    volumes:
     - "~/doctest01/web01/html/:/var/www/html"
    container_name: "web01"

