version: '3.1'

services:

  db01:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    command: "--innodb_use_native_aio=0"
    volumes:
     - "$HOME/doctest01/db01/db-data:/var/lib/mysql"
    ports:
      - 3306:3306
    container_name: "db01"


  adminer01:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    container_name: "adminer01"


#  db01:
#    image: mysql:8.0
#    command: --default-authentication-plugin=mysql_native_password
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: example
#    volumes:
#     - "$HOME/doctest01/db01/db-data:/var/lib/mysql"
#    container_name: "db01"

#  adminer01:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080
#    container_name: "adminer01"

  web01:
    build: ./web01/build
    restart: always
    ports:
      - 80:80
    volumes:
     - "./web01/html/:/var/www/html"
    container_name: "web01"

